dist: xenial

language: java

jdk: openjdk8

notifications:
  email:
    on_success: never
    on_failure: always

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libx11-dev libxpm-dev libxrandr-dev libpango1.0-dev
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libX11.so /usr/lib/libX11.so
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libXpm.so /usr/lib/libXpm.so
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libXft.so /usr/lib/libXft.so
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libXrandr.so /usr/lib/libXrandr.so
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libpango-1.0.so /usr/lib/libpango-1.0.so
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libpangoxft-1.0.so /usr/lib/libpangoxft-1.0.so
  - sudo ln -s /usr/lib/x86_64-linux-gnu/glib-2.0 /usr/lib/glib-2.0
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libgio-2.0.so /usr/lib/libgio-2.0.so
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libglib-2.0.so /usr/lib/libglib-2.0.so
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libgmodule-2.0.so /usr/lib/libgmodule-2.0.so
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libgobject-2.0.so /usr/lib/libgobject-2.0.so
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libgthread-2.0.so /usr/lib/libgthread-2.0.so
